version: '2.2'
services:

  frontend:
    image: ilyailyukou/frontend:0.1
    container_name: frontend
    ports:
        - '3000:3000'
        - '3001:3001'

  resource:
    image: minio/minio
    container_name: resource
    command: server /data
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER : aws_s3_access_key
      MINIO_ROOT_PASSWORD : aws_s3_secret_key
    restart: always

  mysql:
    image: mysql:8.0.21
    container_name: mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
      - "33060:33060"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: iot
      MYSQL_USER: iot
      MYSQL_PASSWORD: password
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3306" ]
      interval: 30s
      timeout: 10s
      retries: 5

  elasticsearch:
    image: elasticsearch:7.9.2
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: always
    environment:
      discovery.type: single-node
      transport.host: 0.0.0.0
      cluster.name: elasticsearch
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9200" ]
      interval: 30s
      timeout: 10s
      retries: 5

  activemq:
    image: rmohr/activemq:5.15.6
    container_name: activemq
    ports:
      - "61616:61616"
      - "8162:8162"
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:61617" ]
      interval: 30s
      timeout: 10s
      retries: 5

  api:
    image: ilyailyukou/api:0.1
    container_name: api
    command: -timeout 60s
    ports:
      - "8080:8080"
    environment:
      TZ: Atlantic/Reykjavik # UTC
    #        SPRING_APPLICATION_JSON: '{
    #              "spring.datasource.url": "jdbc:mysql://db:3306/table",
    #            }'
    restart: always
    depends_on:
      - mysql
      - elasticsearch
      - activemq
      - resource